[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["langchain", "@langchain/openai", "faiss-node"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"