[build]
  publish = "src"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    x-robots-tag = "index"

[[headers]]
  for = "/dist/bundle.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 8000
  port = 8888
  publish = "src"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200