[build]
  publish = "src"
  command = "npm run build"
  functions = "netlify/functions"

[[headers]]
  for = "/dist/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
    [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://scripts.simpleanalyticscdn.com https://cdn.skypack.dev https://ingesteer.services-prod.nsvcs.net; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' https://queue.simpleanalyticscdn.com https://downloadr2.apkmirror.com https://seeklogo.com; connect-src 'self' https://ingesteer.services-prod.nsvcs.net https://voidai.xyz https://heckerai.com https://fresedgpt.space https://api.shard-ai.xyz https://zukijourney.xyzbot.net https://shadowjourney.xyz/ https://api.shuttleai.app https://api.electronhub.top https://app.oxyapi.uk http://api.llmplayground.net https://api.rimunace.xyz https://api.zanity.net https://cablyai.com https://api.naga.ac https://test.skailar.it https://helixmind.online https://unified.hareproxy.io.vn http://api.tryastra.pro https://api.webraft.in https://nobrandai.com; form-action 'self'; upgrade-insecure-requests;"

[[headers]]
  for = "/dist/bundle.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 8000
  port = 8888
  publish = "src"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-handler/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"