[build]
  publish = "src"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"

[[headers]]
  for = "/dist/bundle.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 8000
  port = 8888
  publish = "src"
  autoLaunch = true

[[redirects]]
  from = "/api/submit-form"
  to = "/.netlify/functions/submission-created"
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-handler/:splat"
  status = 200

[functions]
  directory = "netlify/functions"